// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhatTinMvc.Web.Data;

#nullable disable

namespace NhatTinMvc.Web.Data.Migrations
{
    [DbContext(typeof(MvcDbContext))]
    [Migration("20260708025148_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NhatTinMvc.Web.Data.Entities.BillStatusEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BillCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DedupeKey")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<long?>("PushTime")
                        .HasColumnType("bigint");

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StatusTime")
                        .HasColumnType("bigint");

                    b.Property<int?>("TrackedBillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasFilter("[DedupeKey] IS NOT NULL");

                    b.HasIndex("TrackedBillId");

                    b.ToTable("BillStatusEvents");
                });

            modelBuilder.Entity("NhatTinMvc.Web.Data.Entities.TrackedBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BillCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastStatusAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LastStatusId")
                        .HasColumnType("int");

                    b.Property<string>("LastStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("RawCreateResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BillCode")
                        .IsUnique();

                    b.ToTable("TrackedBills");
                });

            modelBuilder.Entity("NhatTinMvc.Web.Data.Entities.BillStatusEvent", b =>
                {
                    b.HasOne("NhatTinMvc.Web.Data.Entities.TrackedBill", "TrackedBill")
                        .WithMany("Events")
                        .HasForeignKey("TrackedBillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TrackedBill");
                });

            modelBuilder.Entity("NhatTinMvc.Web.Data.Entities.TrackedBill", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
