// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhatTinSandbox.Infrastructure.Persistence;

#nullable disable

namespace NhatTinSandbox.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SandboxDbContext))]
    [Migration("20260706123855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillReturn")
                        .HasColumnType("TEXT");

                    b.Property<int>("BillType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CargoContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("CargoTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CargoValue")
                        .HasColumnType("REAL");

                    b.Property<double>("CodAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpectedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<int>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsInstallation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsReturnDoc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsReturnOrg")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<double>("MainFee")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<double>("OtherFee")
                        .HasColumnType("REAL");

                    b.Property<int>("PackageNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverProvinceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverWardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnProvinceCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnWardCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderProvinceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderWardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalFee")
                        .HasColumnType("REAL");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BillCode")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.BillStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<double>("ShippingFee")
                        .HasColumnType("REAL");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillStatusHistories");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Code");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.MasterDataItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Code");

                    b.ToTable("MasterData");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.PartnerAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PartnerAccounts");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.WebhookDeliveryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BillCode");

                    b.ToTable("WebhookDeliveryLogs");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.WebhookSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.BillStatusHistory", b =>
                {
                    b.HasOne("NhatTinSandbox.Domain.Entities.Bill", "Bill")
                        .WithMany("Histories")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("NhatTinSandbox.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
